local _rng = math.random(1,3)
if _rng == 1 then
    warn("Don't skid this or we will steal your virginity!")
elseif _rng == 2 then
    warn("You looking hella fine!!! jk")
elseif _rng == 3 then
    warn("skid mark 1")
end
if game.PlaceId == 617834035 then
    print('Game is indeed '..game.Name)
    loadstring(game:HttpGet('https://raw.githubusercontent.com/KrakenDev0001/Molten/main/Loader.luau'))()
else
    error("Fuck u and yo nigga ass "..game.Name.." looking auto executor")
end;